// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

// AddProjectMemberRequest defines model for AddProjectMemberRequest.
type AddProjectMemberRequest struct {
	Role   string `json:"role"`
	UserId int64  `json:"user_id"`
}

// CreateCommentRequest defines model for CreateCommentRequest.
type CreateCommentRequest struct {
	AuthorId int64  `json:"author_id"`
	Text     string `json:"text"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	AssigneeId  *int64  `json:"assignee_id,omitempty"`
	Description *string `json:"description,omitempty"`
	ProjectId   int64   `json:"project_id"`
	Title       string  `json:"title"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

// UpdateTaskStatusRequest defines model for UpdateTaskStatusRequest.
type UpdateTaskStatusRequest struct {
	Status string `json:"status"`
}

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// AddProjectMemberJSONRequestBody defines body for AddProjectMember for application/json ContentType.
type AddProjectMemberJSONRequestBody = AddProjectMemberRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// CreateCommentJSONRequestBody defines body for CreateComment for application/json ContentType.
type CreateCommentJSONRequestBody = CreateCommentRequest

// UpdateTaskStatusJSONRequestBody defines body for UpdateTaskStatus for application/json ContentType.
type UpdateTaskStatusJSONRequestBody = UpdateTaskStatusRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest
